const BOOKING_STATUS = {
  DRAFT: "DRAFT",
  PENDING_KYC: "PENDING_KYC",
  KYC_IN_PROGRESS: "KYC_IN_PROGRESS",
  KYC_VERIFIED: "KYC_VERIFIED",
  KYC_REJECTED: "KYC_REJECTED",
  PENDING_ASSIGNMENT: "PENDING_ASSIGNMENT",
  ASSIGNED: "ASSIGNED",
  PARTNER_EN_ROUTE: "PARTNER_EN_ROUTE",
  ARRIVED: "ARRIVED",
  TRIP_STARTED: "TRIP_STARTED",
  TRIP_COMPLETED: "TRIP_COMPLETED",
  CANCELLED_BY_USER: "CANCELLED_BY_USER",
  CANCELLED_BY_PARTNER: "CANCELLED_BY_PARTNER",
  CANCELLED_BY_ADMIN: "CANCELLED_BY_ADMIN",
  FAILED: "FAILED",
};

const PARTNER_STATUS = {
  OFFLINE: "OFFLINE",
  ONLINE: "ONLINE",
  BUSY: "BUSY",
  SUSPENDED: "SUSPENDED",
  PENDING_APPROVAL: "PENDING_APPROVAL",
};

const KYC_STATUS = {
  NOT_STARTED: "NOT_STARTED",
  SCHEDULED: "SCHEDULED",
  IN_PROGRESS: "IN_PROGRESS",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
};

module.exports = { BOOKING_STATUS, PARTNER_STATUS, KYC_STATUS };
